### ISSUE TITLE
redesign footer or align footer buttons to center 

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#100]

**Comment by poojakp94** [comment]
I would like to work on this.

**Comment by ravisaxena23** [comment]
sure

**Comment by poojakp94** [comment]
@ravisaxena23 can you elaborate on the redesign you are looking for?
 and I can see that the buttons are already centered.

**Comment by ravisaxena23** [comment]
if we see email buttons and copyright they didin't have equal spacing plus.button should look centerd in respect to text. you can decrease the size of footer.

**Comment by ravisaxena23** [comment]
dougfabris there is some in instalation error please check.or i have to abrot it.

**Comment by dougfabris** [comment]
Yep, I saw that. I'll check, please wait.

**Comment by ravisaxena23** [comment]
and the buttons were not align properly in dextop they were in column not in row
