### ISSUE TITLE
Beautify The Code

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#108]

**Comment by manisacharya** [comment]
Hello @ravisaxena23, can you explain more on this?

**Comment by ravisaxena23** [comment]
Please Fork New Code and please check for conflicts

**Comment by ravisaxena23** [comment]
sure..what you have to do is beautify the code i.e every tag should be in hierarchy there should be proper spacing in all tags(1 -2 tabs) code should not scroll sideways etc..did you get it??

**Comment by manisacharya** [comment]
Thanks @ravisaxena23. I will look into it.
