### ISSUE TITLE
Beautify Page Headings

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#109]

**Comment by dougfabris** [comment]
Hey, can you describe what do you need here?!

**Comment by ravisaxena23** [comment]
Please Fork New Code and please check for conflicts

**Comment by ravisaxena23** [comment]
Different pages uses different heading such as our achievements our alumni..what you have to do is create new headings or beautify the current one. as right now they look little odd with our pages

**Comment by dougfabris** [comment]
I got it. Just assign me and I'll work on that

**Comment by ravisaxena23** [comment]
sure ..remember to check headings in mobile view too
