### ISSUE TITLE
Make a new Login Popup

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#120]

**Comment by rannie-peralta** [comment]
Can I work on this one?

**Comment by ravisaxena23** [comment]
yes sure

**Comment by rannie-peralta** [comment]
What exactly you want me to change from the existing login popup?

**Comment by ravisaxena23** [comment]
it looks very odd with our current website.plus in mobile view once we open it we cannot go back. you can make a new login popup as per you creativity which look good with website.and add cross button so that it should get closed if open in mobile. remember it should be responsive

**Comment by rannie-peralta** [comment]
Alright! Let me try my best.

**Comment by ravisaxena23** [comment]
all the best
