### ISSUE TITLE
Create New contact us page or redesign current page

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#123]

**Comment by thesimpledev** [comment]
I'm up for this! Can I take this over?

**Comment by thesimpledev** [comment]
![Screen Shot 2019-10-04 at 7 39 16 AM](https://user-images.githubusercontent.com/37192643/66216312-1ab55200-e67a-11e9-9772-066f99e70e69.png)

I found the layout breaks here and there. I'll get working on it!

**Comment by ravisaxena23** [comment]
Thankyou so much please dont fork master please work on development 1.0 it will be easy and will not give us conflict..im soory i didn't tell you soon as..i was
