### ISSUE TITLE
Create a profile page

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#131]

**Comment by ravisaxena23** [comment]
create  a profile page..when a person tap on the team memeber or alumni it sholud open there profile page with there names. remember team content is dynamic it will be fetched from backend once completed..try to make team page looks good

**Comment by ravisaxena23** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/44205807/66255552-72e77380-e7a2-11e9-8029-4afb08207382.png)
when some one tap on ravi it should open a page in which my details are shown!!! you can add temp data ..it should show my name , semister ,etc etc..it is a public profile

**Comment by hendaoui** [comment]
I'm working on it :)

**Comment by ravisaxena23** [comment]
all the best

**Comment by hendaoui** [comment]
![image](https://user-images.githubusercontent.com/6974404/66260139-6b2fcb00-e7b2-11e9-98cc-4f0513a34e54.png)

The work is done and a new pull is requested (i think i messed up with branches :p)

**Comment by ravisaxena23** [comment]
no issue sir I'm here to help all day night..let me check i will get back to you soon

**Comment by ravisaxena23** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/44205807/66260717-02f7de00-e7e0-11e9-93c5-822146ec1623.png)
 check this too

**Comment by hendaoui** [comment]
Alright I'm gonna fix it

**Comment by ravisaxena23** [comment]
All the best
