### ISSUE TITLE
make Redux Form of Website

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#133]

**Comment by fgkolf** [comment]
Hi there,
Can you provide some more details on this issue?

**Comment by ravisaxena23** [comment]
yeahh sure have you ever tried react redux?? we have made the components all you have to do it make them in react redux form

**Comment by fgkolf** [comment]
Yes, i have prior experience in react-redux. So you want to migrate all form elements of your app to react-redux-form?

**Comment by ravisaxena23** [comment]
yes can you do that for us it will be a greatest help

**Comment by ravisaxena23** [comment]
Please work on development 1.0 and pull the latest code some work has already done i tried it

**Comment by fgkolf** [comment]
As far as i see, in development 1.0,  there is no redux infrastructure at all. Is there any specific reason you would like to keep form state in redux? If not, consider using something like react-final-form https://final-form.org. Here is the reason why written by the maker of redux-form https://final-form.org/docs/react-final-form/philosophy.
