### ISSUE TITLE
Make admin pannel

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#136]
![WhatsApp Image 2019-10-05 at 19 14 44](https://user-images.githubusercontent.com/44205807/66256492-e9d53a00-e7ab-11e9-9a3e-8f4eba89f436.jpeg)
it should look something like this no need of graphs just a side bar and some cards

**Comment by ravisaxena23** [comment]
fork Devlopment1.0 or honey bhiya. apnnel should contain sidebar too

**Comment by ravisaxena23** [comment]
this pannel should only come in navbar after person login so make a dummy login data after which it should come in navbar and after click the pannel should be seen

**Comment by curranlipsett** [comment]
I'll take this one!

**Comment by ravisaxena23** [comment]
all the best..just remember the button should be visible after login and dashboard should look like this dont add graphs etc it will be to hectic for u just add 1 2 cards with lorem epsulm etc

**Comment by curranlipsett** [comment]
Sorry - I'm going to have to drop this one. It is over my head when it comes to React.
