### ISSUE TITLE
design admin pannel

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#143]
![WhatsApp Image 2019-10-05 at 19 14 44](https://user-images.githubusercontent.com/44205807/66258245-670aaa00-e7c0-11e9-8fe7-dc2c42a1ea1b.jpeg)
try creating like this all things are done you just have to design it...no need to add graphs or content just add 1 2 cards to add event.

**Comment by nik72619c** [comment]
would like to work on this one

**Comment by ravisaxena23** [comment]
sure give it a shot i'm here to help. fork new code. you have to work on development1.0

**Comment by ravisaxena23** [comment]
soory if you get run error there were small issue i have corrected them you can work now aand show off your creativity to us

**Comment by nik72619c** [comment]
Thanks ! Do I need to make all the components shown in the image ?

**Comment by ravisaxena23** [comment]
No No, Just the side bar with different buttons , capacity(replace by event) revenue card(achievements)..just make sure when the person login only then this panel is shown else not. for that you can make dummy login data no issue login has been made..is that fine?

**Comment by nik72619c** [comment]
cool

**Comment by nik72619c** [comment]
What should I do for the login mechanism ? Is the admin gonna have a separate login pannel or the one already present in the website ?

**Comment by nik72619c** [comment]
How can I view the admin dashbooard ?

**Comment by nik72619c** [comment]
Login button doesn't seem to have any function attached . How are you handling loggging in of the user ?

**Comment by ravisaxena23** [comment]
Please pull new code.. It has login temp login u can create ur own guest ID
too
