### ISSUE TITLE
Convert all and make context api

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#146]

**Comment by rakaar** [comment]
I would like to work on this issue

**Comment by ravisaxena23** [comment]
Yes sure u can work.. All the best

**Comment by rakaar** [comment]
Context API by react is used to problem of  `prop drilling`, where one needs to pass componenents several levels down the parent. Here in the current code base, I couldn't find places where such thing is needed. Infact I couldn't find a place where props is passed and use. This is my opinion. Correct me if I am wrong. @ravisaxena23

**Comment by ravisaxena23** [comment]
you are absolutely right sir . we are currently not having the backend I,m working on it what we need is that make code base in a way that when i put api it should become in a form of context api..can it be done assuming we have all the required fields?

**Comment by honeycoder96** [comment]
Closing for now.
Once I implement the login/register after implementing the backend will see if we need this.

**Comment by rakaar** [comment]
> e a

This depends on the complexity of state in the project. Even if api is integrated,  things can be done without context api also. If things grow complex, then its context api is recommended. Till then I believe general React will serve the purpose.
