### ISSUE TITLE
Bug in Contact us page

### ISSUE THREAD

**Issue by rakaar** [technojam/technojam-frontend#149]
While clicked on Contact Us button on navbar, this is being displayed. 
![Screenshot from 2019-10-06 10-39-10](https://user-images.githubusercontent.com/44907757/66264597-e2527700-e825-11e9-867e-808eaa17b60e.png)

**Comment by rakaar** [comment]
Suggest a solution, I would like to work on it

**Comment by rakaar** [comment]
#150

**Comment by ravisaxena23** [comment]
thankyou
