### ISSUE TITLE
create new profile page or redesign the current one

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#153]
![Screenshot (37)](https://user-images.githubusercontent.com/44205807/66265944-04ef8a80-e83c-11e9-9890-480cd13c94c2.png)
make profile page responsive
![Screenshot (38)](https://user-images.githubusercontent.com/44205807/66265948-0caf2f00-e83c-11e9-99ed-45e5e28beba6.png)
it dont look great with our theme ..it should look good on mobiles too.(no scrollable from lefft to right only scroll up and down)

**Comment by bulliana** [comment]
I will take this one!

**Comment by ravisaxena23** [comment]
sure all the  best
