### ISSUE TITLE
make Live events part as shown in image

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#154]
![Screenshot (39)](https://user-images.githubusercontent.com/44205807/66265973-67488b00-e83c-11e9-990b-52c49cdebf5c.png)
it should not look same but the concept should be same

**Comment by ardnahcivar** [comment]
what about the content, inside the live event pages, would be also of the same format?

**Comment by ravisaxena23** [comment]
Yes it will be fetch from backend once completed.. For now you can copy jso  file from events page

**Comment by ardnahcivar** [comment]
@ravisaxena23  created pull request #167, please take a look into it
