### ISSUE TITLE
add bottom up button

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#155]
![Screenshot (40)](https://user-images.githubusercontent.com/44205807/66265996-a37beb80-e83c-11e9-8c63-3623a3c859d7.png)
arrow which take you to the staring of page

**Comment by nik72619c** [comment]
I'll give it a try

**Comment by ravisaxena23** [comment]
all the best

**Comment by ravisaxena23** [comment]
u r not making admin pannel?? should i try?

**Comment by nik72619c** [comment]
Working on that as well :)

**Comment by Mr-Magnificent** [comment]
Is is issue taken? I'd like to attempt it.

**Comment by ravisaxena23** [comment]
try your best @Mr-Magnificent everyone can work on issue. you can also try live event .

**Comment by Mr-Magnificent** [comment]
Is this issue done?

**Comment by ravisaxena23** [comment]
Nope issue is not done yet.. The code for this issue is not writen yet you have to write it. Use development branch to do so

**Comment by ravisaxena23** [comment]
on above image i have just shown what you have to add the image in complete imaginary not related to code

**Comment by Mr-Magnificent** [comment]
![Screenshot_20191007_170728](https://user-images.githubusercontent.com/23209858/66308587-20829000-e925-11e9-8d8c-62cfb4928ea4.png)
When I try to run the local development server after cloning the repo. The home page shows this webpage not the "The cards" one. What am I missing here?

**Comment by ravisaxena23** [comment]
You are missing nothing you have to create the functionality as shown in
the cards at this website.

**Comment by ravisaxena23** [comment]
There should b a circular modal which take us at the top of the website.
You have to add this functionality in this website

**Comment by Mr-Magnificent** [comment]
Let me just confirm again. All the task requires is to a "go to top" hover button at the bottom of the page in the technojam website?
![Screenshot_20191007_170728](https://user-images.githubusercontent.com/23209858/66310074-df8c7a80-e928-11e9-89d0-b65a96237dee.png)

**Comment by nik72619c** [comment]
is it gonna be on every page ?

**Comment by nik72619c** [comment]
ref #164 @ravisaxena23 please have a look

**Comment by ravisaxena23** [comment]
thank you it was nice
