### ISSUE TITLE
redesign event page

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#157]
![Screenshot (41)](https://user-images.githubusercontent.com/44205807/66266024-f05fc200-e83c-11e9-8066-7ff451af9651.png)
![Screenshot (42)](https://user-images.githubusercontent.com/44205807/66266027-f48bdf80-e83c-11e9-8fb2-1ebd15eecba7.png)
redesign event page with same concept so that it look cool and show upcoming and past events

**Comment by branis97** [comment]
Hello, can I work on this one?

**Comment by ravisaxena23** [comment]
Yes it is all yours

**Comment by ravisaxena23** [comment]
Use development1. 0 branch

**Comment by branis97** [comment]
Got it. Thank you!

**Comment by branis97** [comment]
Hello @ravisaxena23! I just opened PR #178. Check it out! I hope you will be happy with redesign🙂.

**Comment by branis97** [comment]
If you will like my work I would like to contribute more to this project. I saw that you are not using any linter tool like ESLint or code formatter like Prettier. I can add them to project. Code will be more readable and with same styling. This will make contribution even more easier. Have a nice day!

**Comment by ravisaxena23** [comment]
It is a beauty of open source that we can contribute many things. And we
are pleased to work with you. I'm happy you are with us in this project. I
will surely check your pr once I'm free. Right now I'm in college classes.
I have my own startup apart from it. And yes we need a prettier you are
free to add things that really matters. I will be more than happy to work
with you. If you need anything else please contact me. And try to work in
our latest branch development1.0...thank you for your support and code.
It's beautiful.

**Comment by branis97** [comment]
You are welcome🙂! Looking forward to our further collaboration.

**Comment by ravisaxena23** [comment]
Our pleasure
