### ISSUE TITLE
Add preloaders

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#169]
![Screenshot_20191009-235850](https://user-images.githubusercontent.com/44205807/66509543-ea920700-eaf0-11e9-995e-fcd3e9479ecf.png)
Add something like this.. Not same but good one.. It should look cool

**Comment by ravisaxena23** [comment]
https://dscnsec.com/
Take inspiration from here

**Comment by jpjjulie** [comment]
Hey, Can I try to work on this?

**Comment by honeycoder96** [comment]
Yes for sure @jpjjulie
