### ISSUE TITLE
Team page thumbnail and name overlap

### ISSUE THREAD

**Issue by zhonghaoliu** [technojam/technojam-frontend#170]
![image](https://user-images.githubusercontent.com/25513105/66529418-5c5a5880-ead1-11e9-8705-77fd2270b20a.png)

Hi there, I found this issue from your website and I would like to solve it for Hacktoberfest.

**Comment by honeycoder96** [comment]
Hi, @zhonghaoliu just pull the latest code from **Development1.0** branch as I can't regenerate the same issue on my system. But if it still persists just leave a comment here and you can work on it.
