### ISSUE TITLE
Resolve Logout Bug

### ISSUE THREAD

**Issue by honeycoder96** [technojam/technojam-frontend#171]
**Branch** : Development1.0

**ReGenerate Bug** : Login/Register once and click on logout. It logs you out first and clears the token from localstorage but again calls the loaduser action.

**Reason**: loadUser action is being called in useEffect hook so that if user reloads the page or comes back again to the website and remain login.
But due to same reason on clicking logout its again calling the loadUser.

**Solution Desired**: on click of logout it should call the logout action and the token and user state should be set to null.

**Comment by Sjain020188** [comment]
Can I try this?

**Comment by ravisaxena23** [comment]
sure

**Comment by Sjain020188** [comment]
Thanks! I will attempt it on weekend.

**Comment by honeycoder96** [comment]
This issue has been resolved with https://github.com/technojam/technojam-frontend/commit/ad2b9ed28a5ce8ce3283cc5bfcb9e20d0419d96c , just pull the latest code from development branch.
