### ISSUE TITLE
Admin dashboard drawer position

### ISSUE THREAD

**Issue by honeycoder96** [technojam/technojam-frontend#180]
**Component**: Dashboard.js
**Access**: Login with admin credentials(admin@admin.com,admin) and on top menu click Dashboard

**Current State**: The sidebar/drawer scrolls with page and the size is fixed as well.

**Desired State**: Create a [clipped drawer](https://material-ui.com/components/drawers/) which remains fixed on the scroll.

**Comment by ardnahcivar** [comment]
I will take this one.

**Comment by honeycoder96** [comment]
Ok @ardnahcivar do ahead.

**Comment by ardnahcivar** [comment]
@honeycoder96 raised the pull request #182
