### ISSUE TITLE
Put about us (3 icon) content in a paper or card with opacity 0.8

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#185]
![Screenshot (47)](https://user-images.githubusercontent.com/44205807/66719502-7025f780-ee0e-11e9-9437-7639ac9a192e.png)

as u can see 3 icon with data put those 3 in a single card

**Comment by basiliskav** [comment]
I am working on this one

**Comment by ravisaxena23** [comment]
Ok

**Comment by phondani0** [comment]
> I am working on this one

I have made the pull request, didn't know you were working on it

**Comment by basiliskav** [comment]
> > I am working on this one
> 
> I have made the pull request, didn't know you were working on it

it's ok dude. I created a PR also. But you should not start to work on an open source issue without notifying the others first.
