### ISSUE TITLE
make form look good in dashboard event

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#186]
![Screenshot (48)](https://user-images.githubusercontent.com/44205807/66719569-3ef9f700-ee0f-11e9-8f1d-93bd8f861d3e.png)

**Comment by anikerr** [comment]
Hello, can I work on this? Was there anything specific you want done to the form, or just fix up the CSS?

**Comment by ravisaxena23** [comment]
Just make form in center and make it look cool.. Yes please fix up css too

**Comment by anikerr** [comment]
Got it, thanks!

**Comment by alexandramj92** [comment]
@ravisaxena23 I am also interested in this issue. Can you assign it to me? Thanks!

**Comment by ravisaxena23** [comment]
@alexandramj92 go ahed

**Comment by alexandramj92** [comment]
> > @alexandramj92 go ahed
> 
> thanks!



> @alexandramj92 go ahed

just made created the pull request for this issue

**Comment by ravisaxena23** [comment]
@alexandramj92 thanks
