### ISSUE TITLE
Make profile Table responsive

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#191]
to login at dashboard use id-: admin@admin.com, password :- admin go to profile
![Screenshot (49)](https://user-images.githubusercontent.com/44205807/66752765-dc0c6c80-eeaf-11e9-815b-569b2700104c.png)
 make this page responsive right now it look like this
![Screenshot (50)](https://user-images.githubusercontent.com/44205807/66752808-f1819680-eeaf-11e9-8704-cc0e31972273.png)

**Comment by ardnahcivar** [comment]
I'll work on this

**Comment by ravisaxena23** [comment]
Okay

**Comment by dsouzajoy** [comment]
Hey, I will work on this one.

**Comment by ravisaxena23** [comment]
Sure..

**Comment by ardnahcivar** [comment]
checked the issue on the dashboard page, there is no icon for the profile page
![image](https://user-images.githubusercontent.com/19891982/66758847-b9348500-eebc-11e9-80ef-c5bc5cc26611.png),

**Comment by ravisaxena23** [comment]
Use development1. 0 branch not master

**Comment by ravisaxena23** [comment]
Got it?

**Comment by ardnahcivar** [comment]
yes

**Comment by ardnahcivar** [comment]
@ravisaxena23 raised the PR #192
