### ISSUE TITLE
Add animation on hover

### ISSUE THREAD

**Issue by honeycoder96** [technojam/technojam-frontend#194]
**WHERE**: /src/Components/Layouts/Footer.js 

**CURRENT STATE**: No animation on interaction.

**DESIRED STATE**: Add simple bounce animation on hover of the social icons

**Comment by PavanKKamra** [comment]
Hey Honey Sharma, 

I would like to attempt to fix this issue. :).

**Comment by luismanfroni** [comment]
Made a pull request for this task #195
