### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by Ritwik880** [technojam/technojam-frontend#232]
Before dark mode:
![Screenshot from 2020-09-28 20-39-15](https://user-images.githubusercontent.com/54446880/94450290-b49ad680-01ca-11eb-91a6-141461c6645f.png)

After dark mode on:
![Screenshot from 2020-09-28 07-47-34](https://user-images.githubusercontent.com/54446880/94450317-c0869880-01ca-11eb-9687-96fe2a9771f6.png)

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.
