### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#233]
Add input validation of the data received while creating a new account to ensure only properly formed data is entering the workflow.

Entries to be verified:
- Name should not be of length less than 3.
- Should be a valid email address.
<p align="center">
<img width="460" height="500" src="https://user-images.githubusercontent.com/39180629/94464756-82927000-01dc-11eb-81cf-85a522a37583.png">
</p>

**Comment by jz543fm** [comment]
Working on this

**Comment by jz543fm** [comment]
File in /src/TopMenu.js

`	const handleRegister = e => {
		e.preventDefault();
		if(name.length <= 3){
			setAlert('Name should not be of length less than 3.', 'danger');
		}
		const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
		re.test(String(email).toLocaleLowerCase);
		if(re.test(email) == false){
			setAlert('Not valid email address!', 'danger');
		}
		
		if (name === '' || email === '' || password === '') {
			setAlert('Please fill in all fields', 'danger');
		} else {
			console.log('register called');
			showLoading({ data: true });
			register({
				name,
				email,
				password
			});
		}
	};`

**Comment by jz543fm** [comment]
Can it be considered as fix for this issue?

**Comment by illegalcall** [comment]
I'll be happy to contribute.

**Comment by lakshya-20** [comment]
> Can it be considered as fix for this issue?

Yes, it's working fine!
Thanks
