### ISSUE TITLE
Re enter password

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#234]
Add a re-enter password field and validation to verify both passwords.
If the password does not match, the user should not be able to create his account.
<p align="center">
<img width="800" height="600" src="https://user-images.githubusercontent.com/39180629/94465701-ef5a3a00-01dd-11eb-92ed-e005284eb0fa.PNG">
</p>

**Comment by Xaconi** [comment]
Hi! Can you assign me this one? I'm searching open issues for the Hacktoberfest and this one seems valid!

**Comment by lakshya-20** [comment]
Sure!

**Comment by Kingmandeep** [comment]
i want to work on this project

**Comment by alexandramj92** [comment]
@lakshya-20 Hi ! I tried to submit a pull request for this issue. Not sure if I need to be assigned to it first?

**Comment by Xaconi** [comment]
> @lakshya-20 Hi ! I tried to submit a pull request for this issue. Not sure if I need to be assigned to it first?

Let me make a PR tonight (I live In Spain), I'll notify you if I don't have time to do it.

**Comment by Xaconi** [comment]
@lakshya-20 ok, I've made a [PR](https://github.com/technojam/technojam-frontend/pull/242) a few minutes ago. Waiting for validation!

**Comment by lakshya-20** [comment]
Yes, it's working!
