### ISSUE TITLE
Know More button not working on mobile view

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#235]
<p align="center">
<img width="460" height="800" src="https://user-images.githubusercontent.com/39180629/94466341-e9b12400-01de-11eb-98f0-55e1a1ef7996.PNG">
</p>

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.

**Comment by lakshya-20** [comment]
Okay!

**Comment by ampsteric** [comment]
And can I send the PR on 1st October for the count in Hacktoberfest?

**Comment by lakshya-20** [comment]
Okay, you can do it on 1st of October.

**Comment by ampsteric** [comment]
resolved the #235 issue.
Please review it and accept so that my contribution for hacktoberfest can also be counted.

Best regards,
Shashwat.

**Comment by lakshya-20** [comment]
Got your pr and it's working now.
Thanks!
