### ISSUE TITLE
The event component is not responsive to the mobile view.

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#236]
<p align="center">
<img width="460" height="800" src="https://user-images.githubusercontent.com/39180629/94466988-f124fd00-01df-11eb-903d-b317d7419264.PNG">
</p>

**Comment by MitanshiKshatriya** [comment]
Hi, looking for issues for hacktoberfest.  Could I be assigned to this issue?

**Comment by MitanshiKshatriya** [comment]
Hi I have worked with reactjs.  I would like to be assigned to it. Can you elaborate what does downward arrow denote?

**Comment by lakshya-20** [comment]
Hello @MitanshiKshatriya  That down arrow denotes a scroll back to the top button which is supposed to be visible completely on the screen but is shifted a little bit out of the screen.
It is supposed to be like this:
![image](https://user-images.githubusercontent.com/39180629/94482387-d01bd680-01f6-11eb-8265-0e0a03f0f66d.png)

**Comment by MitanshiKshatriya** [comment]
Okay! So shud I start fixing it?

**Comment by lakshya-20** [comment]
Yes, you can.

**Comment by MitanshiKshatriya** [comment]
![image](https://user-images.githubusercontent.com/42690596/94847112-c46f2080-043f-11eb-8958-6ed9d2d05316.png)
I have been trying to run the project on my machine but i am getting 404 page for all branches. I installed the node modules using npm install and npm start.

**Comment by lakshya-20** [comment]
Use command (for master branch)
```
npm run dev
```
Also the port no is set to 3000.

**Comment by abhishekjain35** [comment]
I would like to work on this. Please Assign it to me.

**Comment by abhishekjain35** [comment]
![image](https://user-images.githubusercontent.com/53055241/94900752-2c128380-04b3-11eb-82d9-b796c056c209.png)

**Is it okay should I make PR?** 

> OR

**If I need to make any more changes, please specify.**

**Comment by lakshya-20** [comment]
@abhishekjain35 Yes make a pr

**Comment by abhishekjain35** [comment]
@lakshya-20 I've made the PR. Please review it.

**Comment by lakshya-20** [comment]
@abhishekjain35  
Thanks, man! :)
