### ISSUE TITLE
Data Validation for Contact Us form.

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#239]
Add input validation of the data received while submitting a  contact query to ensure only properly formed data is entering the workflow.

Entries to be verified:

- First Name is mandatory and must of length greater than 2
- Should be a valid email address.
- Must be a valid contact number
- Query should not be empty
<p align="center">
<img width="560" height="500" src="https://user-images.githubusercontent.com/39180629/94685144-9a860300-0346-11eb-95ca-ba06ae186d90.PNG">
</p>

**Comment by alabo-excel** [comment]
Hello lakshya! I would love to work on this issue, can you please assign me to it!

**Comment by arpancodes** [comment]
Hello, I want to do this for hacktoberfest can you please assign it to me? Thanks in advance 😃

**Comment by arpancodes** [comment]
Hey @lakshya-20 even though it wasn't assigned to anyone... I started working on it and completed as well... wanted to ask if we want to validate the contact number with or without country code? currently I am doing it with the country code.

**Comment by lakshya-20** [comment]
Yes! got your pr thanks!
