### ISSUE TITLE
Add Form UI to add Team Members

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#245]
**Make a UI to add Team Members and the required fields are:**
- Name
- Email
- Linkedin Url
- Github Url
- Batch
- Image Url

**Example:**
This is Ui to add events and the add Team Member UI should also look similar to this but with desired fields.
![list_view](https://user-images.githubusercontent.com/39180629/94849181-a6ef8600-0442-11eb-8eeb-ef6c471b4f7c.PNG)

**Current UI**
![Capture](https://user-images.githubusercontent.com/39180629/94849492-21b8a100-0443-11eb-8397-df0b1457ed68.PNG)

**Comment by ruhci28** [comment]
hii, @lakshya-20  can i work on this

**Comment by romasinha** [comment]
Hey @lakshya-20 I am skilled in React and UI Components. Please assign me this issue.

**Comment by ravisaxena23** [comment]
@ruhci28 @romasinha sure go ahead

**Comment by ruhci28** [comment]
Hey @lakshya-20 let me try it

**Comment by ruhci28** [comment]
we should not work on same issue. it just waste some one time

**Comment by ravisaxena23** [comment]
@ruhci28 go-ahead we are not going to reject any PR we won't waste anyone's time. also, nothing is a waste of time you are going to learn something new. you can also look at other issues to we going to add new issues tonight.  although you can start working on it.

**Comment by ravisaxena23** [comment]
@ruhci28 you can look in it #246 too.

**Comment by romasinha** [comment]
@lakshya-20 The dashboard icon is not visible. I registered as a user too. Still unable to figure out where the Drawer component is. Can you help me please?

**Comment by ruhci28** [comment]
![Screenshot 2020-10-02 at 1 22 16 AM](https://user-images.githubusercontent.com/59759735/94856593-d3f56600-044d-11eb-88af-d37cdb0a4245.png)
Hii @ravisaxena23 what is the api for  adding the user.?

**Comment by ravisaxena23** [comment]
@ruhci28 you will find API here https://radiant-thicket-94737.herokuapp.com/
for other issues, you can also mail me at ravisaxena230599@gmail.com

**Comment by ruhci28** [comment]
ok sure

**Comment by ruhci28** [comment]
@ravisaxena23 i have to make changes in user tab or team tab.?

**Comment by ravisaxena23** [comment]
You can do both but for now you can make changes in user tab
