### ISSUE TITLE
Display data in Modal

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#246]
There is a list of events having details and some functionalities like edit, delete and download registered attendees,
The task is to load data from the list to modal.

**The Event list looks like:**
![event_list](https://user-images.githubusercontent.com/39180629/94851765-83c6d580-0446-11eb-800f-b40e7adc7230.PNG)

When clicked on the edit button the details of that particular event should be visible in the modal.
**The UI for modal looks like:**
![edit_event_modal](https://user-images.githubusercontent.com/39180629/94851921-bc66af00-0446-11eb-9a14-501533e07d1a.PNG)

**Comment by kala2** [comment]
Hello, Could you assign it to me please?

**Comment by ravisaxena23** [comment]
@kala2 sure

**Comment by lakshya-20** [comment]
Thanks! @kala2  :)
