### ISSUE TITLE
Add Update Event function 

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#247]
**Add update event function in "src/context/event/"**
The props would include the event details :
{
    "eid":"12431231",
    "type":"Single",
    "name":" workshop",
    "description":"2 day workshop covering basic of HTML,CSS and JavaScript",
    "capacity":"150",
    "venue":"Virtual",
    "timing":"10:00",
    "date":"2020-08-23",
    "isPaid":"No",
    "teamSize":"0",
    "amount":"0",
    "resources":"some url"
}

**Your task** is to pass the props  to "/api/events/update/ :eId" and load the updated events.

**Comment by Abdul-Sen** [comment]
Hi, please assign this task to me.

**Comment by ravisaxena23** [comment]
@Abdul-Sen sure

**Comment by ravisaxena23** [comment]
you just start working

**Comment by lakshya-20** [comment]
Done!
