### ISSUE TITLE
Delete Contact Button is not working

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#248]
**Delete contact button is not working**
![delete](https://user-images.githubusercontent.com/39180629/94858689-0fddfa80-0451-11eb-99f6-d6165edfe94c.PNG)

The "deleteContact" function is at "src/context/auth"
And the endpoint to send request is "/api/contact" which accepts "cids" in format
```
{
    "cids":["aa79fbd6-ea54-4f17-9a1a-7555b3a3d5df"]
}
```

**Comment by daretobedifferent18** [comment]
I would like to work on this issue

**Comment by lakshya-20** [comment]
Go ahead!

**Comment by daretobedifferent18** [comment]
I have logged in and backend server is also working in parallel.
I am not able to get the page that is shown in description of this issue while running locally. Could you pls help me finding it.

**Comment by lakshya-20** [comment]
The page is only visible to the admin user, after registering a user go to
the database and change your role from "user" to "admin".
(After setting the project on your local system)
you can set up the whole project on your system the backend is at
https://github.com/technojam/technojam-backend
