### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#250]
**The Dark Mode button is not working.**
![image](https://user-images.githubusercontent.com/39180629/94859376-0ef99880-0452-11eb-9dec-348d2ecc0226.png)

**Comment by ankitgoel25** [comment]
I would like to work on this issue!

**Comment by lakshya-20** [comment]
Go ahead!

**Comment by bolajiscott** [comment]
is it fixed now,

**Comment by lakshya-20** [comment]
No, you can work on this.

**Comment by NiketanG** [comment]
If no one's assigned to this yet, I could do it.

**Comment by phanlyhuynh** [comment]
Can you assign to me? Thanks

**Comment by lakshya-20** [comment]
Go ahead! @NiketanG @phanlyhuynh

**Comment by phanlyhuynh** [comment]
@lakshya-20 https://github.com/technojam/technojam-frontend/pull/260 I fixed it. Please check for me. Thanks :D

**Comment by NiketanG** [comment]
@lakshya-20 The changes are done. Dark mode working site-wide. #261

**Comment by ravisaxena23** [comment]
@ankitgoel25 hey Ankit sorry this issue is almost over however we have created a new issue #266 I think you are going to like it. please do check

**Comment by ravisaxena23** [comment]
@lakshya-20 should we close it

**Comment by lakshya-20** [comment]
@ravisaxena23 yes we can.
