### ISSUE TITLE
Enhance Live Event

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-frontend#251]
When there are no Live Events there should be some message like "No events now come back soon".
![image](https://user-images.githubusercontent.com/39180629/94859652-7d3e5b00-0452-11eb-9cbc-734c86afaef9.png)

**Comment by KaylaKremer** [comment]
I'll take this one on!

**Comment by paulrrdiaz** [comment]
Hey @lakshya-20 
Could I work on this?

**Comment by lakshya-20** [comment]
Thanks, @KaylaKremer  for your contribution :)
