### ISSUE TITLE
Fix Footer

### ISSUE THREAD

**Issue by lazycipher** [technojam/technojam-frontend#68]
Fix the minimum height of the footer so that It'll be still at the bottom even if there's no content on the page.
For example: Check this image(Team Page). Here footer is not on the bottom.

![Imgur](https://i.imgur.com/uj0gP2m.png)

**Comment by grovertb** [comment]
Please assign this to me

**Comment by lazycipher** [comment]
Ya sure! Go Ahead @grovertb

**Comment by DustinTheGreat** [comment]
damn, I just finished this. have any other bugs?

**Comment by lazycipher** [comment]
@DustinTheGreat, You can try #71

**Comment by urvashigupta7** [comment]
<img width="368" alt="error" src="https://user-images.githubusercontent.com/41363633/66068393-2108d880-e56b-11e9-9c34-492108d47dbb.PNG">

Even after installing all the dependencies. I am getting this error.
Could anybody please tell me the reason for this?

**Comment by DustinTheGreat** [comment]
did you run npm install

**Comment by urvashigupta7** [comment]
> did you run npm install

Yes I did.

**Comment by DustinTheGreat** [comment]
> > did you run npm install
> 
> Yes I did.

and npm install react-scripts@latest?

**Comment by urvashigupta7** [comment]
> > > did you run npm install
> > 
> > 
> > Yes I did.
> 
> and npm install react-scripts@latest?

Getting the same error.

**Comment by DustinTheGreat** [comment]
> > > > did you run npm install
> > > 
> > > 
> > > Yes I did.
> > 
> > 
> > and npm install react-scripts@latest?
> 
> Getting the same error.

Sorry i'm not really a JS guy... but did try running npm install again after npm install react-scripts@latest? really the only other thing I can think of.

**Comment by urvashigupta7** [comment]
> > > > > did you run npm install
> > > > 
> > > > 
> > > > Yes I did.
> > > 
> > > 
> > > and npm install react-scripts@latest?
> > 
> > 
> > Getting the same error.
> 
> Sorry i'm not really a JS guy... but did try running npm install again after npm install react-scripts@latest? really the only other thing I can think of.



> > > > > did you run npm install
> > > > 
> > > > 
> > > > Yes I did.
> > > 
> > > 
> > > and npm install react-scripts@latest?
> > 
> > 
> > Getting the same error.
> 
> Sorry i'm not really a JS guy... but did try running npm install again after npm install react-scripts@latest? really the only other thing I can think of.

It's okay. Thanks :+1:

**Comment by ravisaxena23** [comment]
Guys try the new one and change accordingly for dextop view

**Comment by lazycipher** [comment]
@urvashigupta7 got it working?

**Comment by ravisaxena23** [comment]
yes!!hope so!! i Dont have monitor
