### ISSUE TITLE
Make Team Design look better!

### ISSUE THREAD

**Issue by lazycipher** [technojam/technojam-frontend#71]
Design the Team Page.

It looks like this as of now:

![Imgur](https://i.imgur.com/dtmeQaj.png)

We want to make the profile cool! Please discuss your design before implementing it!

![Imgur](https://i.imgur.com/MUB4ZCP.png)
Don't make it look exactly the same as Alumni Page but take idea from there.

**Comment by gcmartins11** [comment]
What do you think of this design?
![Technojam img](https://user-images.githubusercontent.com/42540236/66262678-3a07c880-e7bb-11e9-8daa-9ab40ff7fd35.png)

**Comment by lazycipher** [comment]
@gcmartins11 Looks good! Can we put image, name and social links inside a material design box?

**Comment by ravisaxena23** [comment]
sir you have to work on alumni page no on team page...please redesign alumni page

**Comment by gcmartins11** [comment]
Sure! I'm working on it!
