### ISSUE TITLE
Make night mode for the website

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#85]

**Comment by tttson** [comment]
hi! could i take a stab at this?

**Comment by ravisaxena23** [comment]
yes sure..but make sure in night mode layout css should not get changes

**Comment by ravisaxena23** [comment]
please fetch development1.0 with it ,it will be easy to create night mode..plus please make sure for conflicts thank you

**Comment by ravisaxena23** [comment]
or please try to make new css file..

**Comment by amreshk005** [comment]
@ravisaxena23 if no one is this can I work on this?

**Comment by ravisaxena23** [comment]
Yes sure..please make sure to work on development1.0 branch

**Comment by ravisaxena23** [comment]
@amreshk005  i checked your pull request you have done a great work. but we are looking for css to one the person tap on button it should change the css to you have to write css to so i have to revert the pull request!! if it is a long task you can create css for basic element such as navbar and footer

**Comment by ravisaxena23** [comment]
@tttson you are doing it brother just need a confirmation!!

**Comment by ravisaxena23** [comment]
@tttson will you help us out ma'am
