### ISSUE TITLE
Make image on homepage load dynamically

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#88]

**Comment by hjJunior** [comment]
Hi, can you please give more details about what you mean if load dynamically? I mean, with an example I can work on it 😬

**Comment by ravisaxena23** [comment]
yes sure...actually write now we don't have back end...what we want is that if we change the background image at the back end it should automatically change at front end we dont want to open code and paste the backgrond image link

**Comment by ravisaxena23** [comment]
understood??

**Comment by ravisaxena23** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/44205807/66125727-6548b700-e605-11e9-88f0-f4e0b841e7dc.png)
as you can see we have put data in a json file. when the backend is ready we will put api that will automatically fetch json and put the data. u have to do the same task u have to put image link in json that can be retrived by api call.

**Comment by ravisaxena23** [comment]
if u understood will you like to work on it???

**Comment by hjJunior** [comment]
=D thx for ur time! I'd like to work on it, can u assigned to me?

**Comment by ravisaxena23** [comment]
sure my pleasure

**Comment by ravisaxena23** [comment]
Thankyou I have merged your pull request it was working good..mean while you can  check for new issue we have created
