### ISSUE TITLE
This code uses a lot of same inline css make css file and put css in it and unify the code

### ISSUE THREAD

**Issue by ravisaxena23** [technojam/technojam-frontend#98]

**Comment by ravisaxena23** [comment]
eg-: we have given font style roboto at all pages separately do something that we have to give font style at one place and it changes the font of all website...you have to do it for all similar css

**Comment by chisom5** [comment]
can i work on this? if you don't mind

**Comment by ravisaxena23** [comment]
yes sure..our pleasure to work with u

**Comment by chisom5** [comment]
alright

**Comment by chisom5** [comment]
i just made a pull request as soon as i am done with it, kindly check it out

**Comment by ravisaxena23** [comment]
I' had to revert your pull request because it changes the base design..card layout is chaged mentorship page is changed achivements are not showing pleaase make new css which do not change the current layout

**Comment by ravisaxena23** [comment]
im soory will you try again?

**Comment by chisom5** [comment]
alright, will look into it

**Comment by chisom5** [comment]
i have made the corrections, so it doesn't affect the previous styles

**Comment by chisom5** [comment]
but i am now creating a new pull request for it, kindly check it out

**Comment by ravisaxena23** [comment]
Thank you  it just worked fine..great effort brother

**Comment by chisom5** [comment]
Thanks for the opportunity
